// Generated by gencpp from file jhr_type_2023/Jhr_point.msg
// DO NOT EDIT!


#ifndef JHR_TYPE_2023_MESSAGE_JHR_POINT_H
#define JHR_TYPE_2023_MESSAGE_JHR_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jhr_type_2023
{
template <class ContainerAllocator>
struct Jhr_point_
{
  typedef Jhr_point_<ContainerAllocator> Type;

  Jhr_point_()
    : X(0.0)
    , Y(0.0)
    , A(0.0)  {
    }
  Jhr_point_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , A(0.0)  {
  (void)_alloc;
    }



   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef float _A_type;
  _A_type A;





  typedef boost::shared_ptr< ::jhr_type_2023::Jhr_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jhr_type_2023::Jhr_point_<ContainerAllocator> const> ConstPtr;

}; // struct Jhr_point_

typedef ::jhr_type_2023::Jhr_point_<std::allocator<void> > Jhr_point;

typedef boost::shared_ptr< ::jhr_type_2023::Jhr_point > Jhr_pointPtr;
typedef boost::shared_ptr< ::jhr_type_2023::Jhr_point const> Jhr_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jhr_type_2023::Jhr_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jhr_type_2023::Jhr_point_<ContainerAllocator1> & lhs, const ::jhr_type_2023::Jhr_point_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X &&
    lhs.Y == rhs.Y &&
    lhs.A == rhs.A;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jhr_type_2023::Jhr_point_<ContainerAllocator1> & lhs, const ::jhr_type_2023::Jhr_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jhr_type_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jhr_type_2023::Jhr_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jhr_type_2023::Jhr_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jhr_type_2023::Jhr_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14206843863907ab243efb1949dfadae";
  }

  static const char* value(const ::jhr_type_2023::Jhr_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14206843863907abULL;
  static const uint64_t static_value2 = 0x243efb1949dfadaeULL;
};

template<class ContainerAllocator>
struct DataType< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jhr_type_2023/Jhr_point";
  }

  static const char* value(const ::jhr_type_2023::Jhr_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 X\n"
"float32 Y\n"
"float32 A\n"
;
  }

  static const char* value(const ::jhr_type_2023::Jhr_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.A);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Jhr_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jhr_type_2023::Jhr_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jhr_type_2023::Jhr_point_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "A: ";
    Printer<float>::stream(s, indent + "  ", v.A);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JHR_TYPE_2023_MESSAGE_JHR_POINT_H
